// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

/**
 * InstallMSYS2 installs (or updates) MSYS2. Windows-only implementation.
 */
export function InstallMSYS2(): $CancellablePromise<void> {
    return $Call.ByID(190300057);
}
