// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

import * as InstallMSYS2Service from "./installmsys2service.js";
export {
    InstallMSYS2Service
};
